### DISCUSSION TITLE
Infra SSH Configuration

### DISCUSSION THREAD

**Discussion by dcardellino** [infrahq/infra#4321] [Q&A] [answered]
Hey together,

Currently I try configure Infra for SSH access some of my Linux Servers.
I configured the infra application on the server according your documentation on https://infrahq.com/docs/integrations/ssh

Now when I start the infra systemd unit I see the following error in the log.

```
Jun 28 10:46:56 hcloud-wireguard-server-stage-0001 infra[158365]: Error: failed to register destination: error listing destinations: unauthorized
```

I created an access key via the UI and updated the `/etc/infra/connector.yaml` the following:

```yaml
kind: ssh
name: stage-bastion
endpointAddr: infra.selfhost.com
server:
  accessKey: generated.accessKey
```

Am I doing something wrong?

**Comment by dcardellino** [comment]
Is this feature not available in the selfhosted version?

**Reply by dcardellino** [reply, marked as answer]
Just a misconfiguration on our side.

**Reply by pdomineaux** [reply]
Hi, what was the configuration issue please ?

**Comment by pdomineaux** [comment]
Ok I've found it:

```yaml
kind: ssh
name: stage-bastion
endpointAddr: your-ssh-hosthost.com
server:
  accessKey: generated.accessKey
  url: https://infra.self-hosted.com/
```
