### ISSUE TITLE
Unexpected behavior for infra access list, destination list, etc

### ISSUE THREAD

**Issue by technovangelist** [infrahq/infra#1168]
I did a helm install with the following values file:
```
server:
  ingress:
    enabled: true
    hosts:
      - localhost # edit me
    className: nginx

  service:
    type: LoadBalancer
  config:
    providers:
      - name: Okta
        url: dev-79107176.okta.com
        clientID: myclientid
        clientSecret: myclientsecret

    grants:
      - user: matt@tmlw.io
        role: admin
        resource: infra
      - user: matt@tmlw.io
        role: admin
        namespace: default
        resource: kubernetes.home

engine:
  ingress:
    enabled: true
    hosts:
      - localhost
    className: nginx
  service:
    type: LoadBalancer
  config:
    name: home
```

If i run `infra list` i see nothing. `infra access list` shows me 
```
infra access list
  PROVIDER  IDENTITY      ACCESS  RESOURCE
  Okta      matt@tmlw.io  admin   kubernetes.home
```
`infra destinations list` shows nothing

if i run `infra access grant -u matt@tmlw.io -r admin kubernetes.home` I get `Access granted!`. 

Still nothing in destinations
`infra list` is still blank

infra-server and infra-engine are definitely running.
