### ISSUE TITLE
Allow creating grants without a role

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1238]
Right now Infra requires a role when `infra grant`, however several users have existing RBAC tooling and want Infra to purely manage authentication.

### User experience changes

```yaml
# grant with no permissions
grants:
  - user: jeff@infrahq.com
    resource: kubernetes.staging
```

```bash
# grant with no permissions
infra grant add kubernetes.staging -u jeff@infrahq.com
```

### Other considerations
- Infra's Kubernetes impersonation headers should match standard fields
