### ISSUE TITLE
Add wildcard support to config file

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#137]
When a wildcard is used in a config attribute it should apply to all entities that match that pattern.

Ex clusters below:
```
users:
  bob@example.com:
    roles:
      writer:
        kind: cluster-role
        clusters:
          - cluster-C*
```

This may not make sense to apply to all attributes.
