### ISSUE TITLE
Consolidate two ways to load providers, users, grants via `helm` chart

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1854]
Remove `additionalProviders`, `additionalUsers`, `additionalGrants` since it's confusing to users they they can do this in two ways today and they aren't "additional" - users want this to be the source of truth for these objects.

Keep this:
```
server:
  config:
    providers: [...]
    users: [...]
    grants: [...]
```

and remove these:
```
server:
  additionalProviders: [...]
  additionalUsers: [...]
  additionalGrants: [...]
```
