### ISSUE TITLE
Specifying an existing access key in config for a different user should fail-fast

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#1983]
## Describe the bug
When an existing access key is specified for a different or new user in config that user fails to be created (which is good because it prevents the access key from changing the identity it was issued for in this case).

Steps to reproduce:
1. Create a config with a user/key:
```
server:
  config:
    users:
      - name: test@example.com
        accessKey: aaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbb
```
2. Apply the config.
`helm upgrade --install -f infra.yaml`
3. Observe that you can successfully login.
4. Update the config to specify a new user, but with the same access key previously used.
```
server:
  config:
    users:
      - name: different@example.com
        accessKey: aaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbb
```
5. Apply the config.
`helm upgrade --install -f infra.yaml`
6. Attempt to login with the access key. It will fail.

## Expected behavior
Infra fails to apply the config and error logs that the access key specified for a user was already in use.
