### ISSUE TITLE
Move Roles to Top Level in the Config File

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#228]
The current config file format does not map very well to the API and CLI operations, is there a better model for this?

Perhaps a more flat format.

Ex:
```
﻿﻿version: v1-alpha

providers:
  okta:
    domain: <Okta domain>
    clientID: <Okta client id>
    clientSecret: <Okta client secret>
    apiToken: <Okta api token>

roles:
  # name or role? what do people call it in other APIs?
  - name: <role name>
    destinations:
      - name: <cluster name>
        namespaces:
          - something
          - something else
        labels:
          - label 1
          - label 2
      - name: <ssh destination name>
    users:
      - bruce@example.com
      # provider not specified
    groups:
      - Everyone
      # provider not specified
```
