### ISSUE TITLE
ui: okta icon is incorrect on the login page

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#2489]
![Image](https://user-images.githubusercontent.com/63033505/177384940-cabe578f-2661-43e9-9b23-200005e0e12f.png)

**Comment by BruceMacD** [comment]
I believe this could be from a bad migration on our dev cluster

**Comment by dkulchinsky** [comment]
@BruceMacD I noticed the same after upgrading from 0.13.5 to 0.13.6

![Screenshot_20220714-195301_Chrome](https://user-images.githubusercontent.com/61992380/179119982-617a3e59-c7df-4217-89e9-5c38cb00bc40.jpg)

**Comment by BruceMacD** [comment]
It seems like this was caused by a change to our config format and can be fixed by specifying the provider kind in config:
```
providers:
      - name: okta
        url: example.okta.com
        clientID: 0aaa
        clientSecret: bbb_
        kind: okta
```

Please let me know if the issue persists.
