### ISSUE TITLE
Namespace scoping doesn't apply rolebinding

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#310]
Example yaml file to reproduce:

```
groups:
  - name: InfraDevelopers
    source: okta
    roles:
      - name: cluster-admin
        kind: cluster-role
        destinations:
          - name: production
            namespaces:
              - infrahq

      - name: default-read-only
        kind: role
        destinations:
          - name: production
            namespaces:
              - default
```

Result:

* No access to `infrahq` namespace even if part of `InfraDevelopers` group
