### ISSUE TITLE
Secret value with `:` is misinterpreted as a secret from a provider

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#3333]
## Describe the bug

If the secret value contains `:`, and the secret is loaded through environment variables, the value will be interpreted as a secret from a secret provider. Since this will probably not resolve to a valid provider, it will fail and the server will refuse to start up. 

e.g. configuring a secret from env using Helm

```
server:
  env:
    - name: INFRA_SERVER_DB_PASSWORD
      value: !@#$%&*()-_=+[]{}<>:?
```

The server will try to load secret `?` from provider `!@#$%&*()-_=+[]{}<>`

## Expected behavior

Two solutions come to mind.

1. Disable secret look when value comes from the environment
2. Use the value verbatim if the provider does not exist.
