### ISSUE TITLE
Wrong connector endpoint address when using NodePort

### ISSUE THREAD

**Issue by l-drews** [infrahq/infra#3731]
## Describe the bug

When adding a connector wich uses a `NodePort` service it is connected via the `default` port `30080` not the `secure` port `30443`. 
In the kubeconfig the server uses the `https` protocol but with the `http` port

```yaml
- cluster:
    certificate-authority-data: ...
    server: https://192.168.101.8:30080 # expecting port 30443 here
  name: infra:example
```

Which leads to this error message:
```sehll
Unable to connect to the server: http: server gave HTTP response to HTTPS client
```

## Expected behavior

The connector should be used with the correct port for its protocol. In this case port `30443` should be used

## Environment
Versions:

```
$ infra version
  Client: 0.18.1
  Server: 0.18.1
```

```
$ kubectl version
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.20.5
```

### Connector

values.yaml:

```yaml
connector: 
  service:
    type: NodePort
  config:
    server: "192.168.102.166"
    skipTLSVerify: true
    logLevel: debug
```

Helm command: 
```shell

helm upgrade \
    --install \
    --namespace infra \
    --create-namespace \
    infra infrahq/infra \
    --set connector.config.accessKey=$INFRA_ACCESS_KEY \
    --set connector.config.name=example \
    -f connector/values.yaml
```

### Server

values.yaml:
```yaml
server:
  ingress:
    enabled: true
  service:
    loadBalancerIP: "192.168.102.166"
  config:
    users:
      - name: admin@infra.int
        password: env:INFRA_ADMIN_PASSWORD

    grants:
      - user: admin@infra.int
        role: admin
        resource: infra

  envFrom:
  - secretRef:
      name: infra-admin-credentials
```

Helm command: 
```shell
helm upgrade \
    --install \
    --namespace infra \
    --create-namespace \
    infra infrahq/infra \
    --values server/values.yaml
```

## Relevant Infra Logs

```
$ infra destinations list
  NAME      KIND        URL                  STATUS     LAST SEEN
  example kubernetes  192.168.101.8:30080  Connected  5 seconds ago
```
