### ISSUE TITLE
Grants not working 

### ISSUE THREAD

**Issue by yeshwanth1312** [infrahq/infra#3751]
i am granting everyone in AD group as admin to infra resource, but I see below error

`infra login server-url` is working though
```
infra keys add --connector --ttl 17520h0m0s
Cannot list keys: missing privileges for GetUser
```
## values.yaml file
```
    ## Additional grants to configure
    grants:

      - group: SSO-Infra-Admin
        role: admin
        provider: azure
        resource: infra
```
Error logs
```
level":"debug","error":"you do not have permission to list users, requires role admin, view, or connector","method":"GET","path":"/api/users","statusCode":403,"remoteAddr":"redacted:43461","time":1669656839790,"caller":"server/routes.go:192","message":"api request error"}
{"level":"info","method":"GET","path":"/api/users","localAddr":"ireddacted","remoteAddr":"redacted","userAgent":"Infra/0.16.2 (cli 0.18.1; darwin/arm64)","userID":"redacted","orgID":"if","elapsed":2.820692,"statusCode":403,"size":106,"time":1669656839790,"caller":"server/logging.go:80","message":"API request completed"}
{"level":"debug","time":1669656898031,"caller":"server/middleware.go:239","message":"Host: iredacted"}
```

```
infra version

 Client: 0.18.1
 Server: 0.18.1
```
