### ISSUE TITLE
Allow users to list only available to them set of namespaces

### ISSUE THREAD

**Issue by igorcoding** [infrahq/infra#4034]
## Is your feature request related to a problem? Please describe.

When granting access to a specific set of namespaces to a user or a group a user does not have a permission to list namespaces, so commands such as `kubectl get ns` or namespaces view in k9s don't work as expected (logically it has to show exactly what is available to the user). 

It is still kind of solvable by creating a separate ClusterRole like the following and binding groups and users with it:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.infrahq.com/include-role: "true"
  name: cluster-namespaces-ro
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
```

But this ClusterRole grants permission to list all namespaces in the cluster. In order to limit the scope to a desired set of namespace a separate ClusterRole must be defined. if I understand it correctly (note the resourceNames in the spec):
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.infrahq.com/include-role: "true"
  name: cluster-namespaces-ro
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames: ["ns-1", "ns-2"]
  verbs:
  - get
  - list
  - watch
```

So it seems like it is not possible to do it automatically outside from infra, because the necessary information about the granted namespaces is contained within infra and we have to do it for each unique set of namespaces essentially. Without this information it is not even possible for a user to tell to which namespaces it has access to (without referring to infra list command).

## Describe the solution you'd like

I'm not sure about an exact solution, but it seems like in order to solve this problem infra needs to manage (create, update and delete) those ClusterRoles for each grantee (a group or a user directly) and then also manage automatically a ClusterRoleBinding to bind a group or a user to this ClusterRole.

## P.S.

Of course, maybe I am all wrong - and this feature is already implemented in some way within infra and I just didn't know how to solve my problem another way around. If that is the case - I would highly appreciate your help on how to achieve a similar behaviour by other means.
