### ISSUE TITLE
Roles with same name but different configurations are ignored

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#440]
Example configuration:
```yaml
  groups:
    - name: Engineering
      roles:
        - name: cluster-admin
          kind: cluster-role
          destinations:
            - name: docker-desktop
              namespace:
                - kube-system

  users:
    - email: <email>
      roles:
        - name: cluster-admin
          kind: cluster-role
          destinations:
            - name: docker-desktop
```

A single role is created despite having different configurations.

```json
[
  {
    "created": 1634082912,
    "destination": {
      "created": 1634082907,
      "id": "BZM53AAdkUGS",
      "kubernetes": {
        "ca": "<redacted>",
        "endpoint": "localhost:8443"
      },
      "name": "docker-desktop",
      "updated": 1634082936
    },
    "groups": [ ... ]
      }
    ],
    "id": "iDaIUchJymI6",
    "kind": "cluster-role",
    "name": "cluster-admin",
    "namespace": "",
    "updated": 1634082912,
    "users": [ ... ]
  }
]
```
