### ISSUE TITLE
Validate config file keys

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#444]
Before importing a config file we should validate that the expected keys are present in the yaml and log and unexpected fields at the `warn` level. 

Ex:
A config file with "type" instead of "kind":
```
sources:
  - type: okta
    domain: dev.okta.com
    clientId: aaa
    clientSecret: infra-registry-okta/clientSecret
    apiToken: infra-registry-okta/apiToken
```

Would result in something like:
```
{"level":"warn","ts":1634130915.3938713,"caller":"registry/config.go:99","msg":"unexpected field 'type' on source. Did you mean `kind`?"}
```
