### ISSUE TITLE
Remove infra: name in cluster contexts

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#546]
Users have asked us to keep the `kubectl` context name inline with the name of their clusters in EKS, AKS, GKE. They have scripts that expect these names and don't want to re-write those scripts to support infra-specific context names.

For rare conflicts (due to existing credentials with kOps OR two clusters in infra with the same name – collisions with AWS/EKS/AKS are rare due to their long cluster names / prefixes), we should append a number based on the sorted ID of the cluster
```
development already exists -> infra creates "development-2" context
```

To help users de-dupe clusters for users (in the rare case where someone can access 2 clusters with the same name), we can add metadata to the `cluster` objects in either:
- Cluster name (note, not context) e.g. `infra:<unique ID>:development`
- Cluster metadata tags in the kubeconfig (see example from kube docs below):
```
clusters:
- name: my-cluster
  cluster:
    server: "..."
    extensions:
    - name: client.authentication.k8s.io/exec
      extension:
        arbitrary: config
        this: can be provided via the KUBERNETES_EXEC_INFO environment variable upon setting provideClusterInfo
        you: ["can", "put", "anything", "here"]
```
