### ISSUE TITLE
Namespace permissions

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#56]
Currently, Infra can only map permissions to cluster-wide roles. Customers require the ability to map users to namespace-specific roles. For example:

```
# example infra.yaml

permissions:
  - user: jeff@infrahq.com
    role: edit
    destination: production
    namespace: frontend       # Additional namespace key
```
