### ISSUE TITLE
Add `Kind` to create destination request

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#571]
`Kind` should be a required part of the request rather than assumed on the server side. 

e.g.
```yaml
DestinationCreateRequest:
  type: object
  required:
    - name
    - kind
    - labels
  properties:
    name:
      type: string
    kind:
      type: string
    labels:
      type: array
      items:
        type: string
    kubernetes:
      $ref: 'destination.yaml#/DestinationKubernetes'
```
