### ISSUE TITLE
container registries support - copying secrets 

### ISSUE THREAD

**Issue by mchiang0610** [infrahq/infra#617]
documenting this for later: 
- for supporting container registries, it's currently a pain for users to copy secrets across multiple namespaces 

It's currently unclear how this will be configured. Maybe something like this?

```
# values.yaml
---
config:
  destinations:
    - name: ghcr
      kind: container-registry
      dockerconfig: |
        ...
      namespaces:
        - default
        - monitoring
    - name: ecr
      kind: container-registry
      labels: [aws, us-west-2]
      dockerconfig: kubernetes:secret/file
      namespaces: []  # default, all namespaces. could also be no namespaces?

  users:
    - email: some.user@infrahq.com
      destinations:
        - labels: [container-registry]  # both ghcr and ecr
    - email: some.other@infrahq.com
      destinations:
        - labels: [aws, us-west-2]  # only ecr
```

Checklist:
- [ ] Configured registries are synced to configured namespaces (or all if not namespaces are not configured)
- [ ] Configured registries are synced to user's local docker.config on login
