### ISSUE TITLE
When no provider is specified on a group-role mapping, apply this mapping on groups from all providers

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#654]
When a group-role mapping does not specify a provider this mapping should be applied to a group from any provider that matches the group name.

Ex:
```
groups:
    - name: Everyone
      roles:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - labels: [kubernetes]
```

This worked previously just because the group was assigned to the first provider found in the database (and we only have one).
