### ISSUE TITLE
Grants in config are not always mapped

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#755]
**Reproduction steps:**

1. Stand up a new instance of Infra with a config:
```
groups:
    - name: saiyans
      provider: okta
      grants:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - kind: kubernetes
  users:
    - email: hello@example.com
      grants:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - kind: kubernetes
```
2.  Update the config with a new user role grant:
```
groups:
    - name: saiyans
      provider: okta
      grants:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - kind: kubernetes
  users:
    - email: bruce@example.com
      grants:
        - kind: pod-reader
          name: cluster-admin
          destinations:
            - kind: kubernetes
    - email: hello@example.com
      grants:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - kind: kubernetes
```

**Result:** 

The grant is created, but the user is not mapped to the grant.

**Notes:**

- Haven't nailed down the exact cause of this yet.It could happen with updated groups too.
