### ISSUE TITLE
Updating grant mappings in config is additive rather than a replacement

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#826]
**Current behavior:**
When a user/group grant mapping is changed in config it is added to the existing grant rather than replacing it.

**Expected behavior:**
Infra grant state should match the grant mappings specified in config exactly.

**Steps to reproduce:**
1. Stand up Infra with a config:
```
config:
  providers:
    ...
  groups:
    - name: Everyone
      provider: okta
      grants:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - kind: kubernetes
```
2. Observe that the grant mapping is applied by listing the grants at the `/v1/grants` endpoint:
```
[
	{
		"id": "7aa4f11a-7ad5-11ec-971e-fa2cc16c6a1f",
		"created": 1642781784,
		"updated": 1642781784,
		"kind": "kubernetes",
		"destination": {
			"id": "7aa4d56d-7ad5-11ec-971e-fa2cc16c6a1f",
			"nodeID": "d573a88c2b0aa6034b706823145f725610298d05f17741651088e7a850124cf9",
			"name": "docker-desktop",
			"kind": "kubernetes",
			"created": 1642781784,
			"updated": 1642781784,
			"labels": null,
			"kubernetes": {
				"ca": "",
				"endpoint": "localhost:8443"
			}
		},
		"kubernetes": {
			"kind": "cluster-role",
			"name": "cluster-admin",
			"namespace": ""
		},
		"groups": [
			{
				"id": "72debead-7ad5-11ec-971e-fa2cc16c6a1f",
				"name": "Everyone",
				"created": 1642781771,
				"updated": 1642781784
			}
		]
	}
]
```
3. Change the config to specify a grant to the same destination, but for a different user/group (this example changes `Everyone` to `saiyans`).
```
config:
  providers:
    ...
  groups:
    - name: saiyans
      provider: okta
      grants:
        - kind: cluster-role
          name: cluster-admin
          destinations:
            - kind: kubernetes
```
4. Apply the config and check the grants endpoint again.
```
[
	{
		"id": "7aa4f11a-7ad5-11ec-971e-fa2cc16c6a1f",
		"created": 1642781784,
		"updated": 1642781784,
		"kind": "kubernetes",
		"destination": {
			"id": "7aa4d56d-7ad5-11ec-971e-fa2cc16c6a1f",
			"nodeID": "d573a88c2b0aa6034b706823145f725610298d05f17741651088e7a850124cf9",
			"name": "docker-desktop",
			"kind": "kubernetes",
			"created": 1642781784,
			"updated": 1642781784,
			"labels": null,
			"kubernetes": {
				"ca": "",
				"endpoint": "localhost:8443"
			}
		},
		"kubernetes": {
			"kind": "cluster-role",
			"name": "cluster-admin",
			"namespace": ""
		},
		"groups": [
			{
				"id": "72debead-7ad5-11ec-971e-fa2cc16c6a1f",
				"name": "Everyone",
				"created": 1642781771,
				"updated": 1642781784
			},
                        {
				"id": "72debead-7ad5-11ec-971e-breiwbr34",
				"name": "saiyans",
				"created": 1642781771,
				"updated": 1642781784
			}
		]
	}
]
```

**Root cause:**
Grants to keep are checked at the entity level (grant ID) while loading config, rather than seeing which mappings still exist.
