### ISSUE TITLE
Assigning groups to `resource: infra` in `infra.yaml` results in "record not found"

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#871]
To reproduce:

1. Create `infra.yaml`:

```
grants:
  - group: Engineering
    role: admin
    resource: infra
```

```
$ infra import infra.yaml
Error: Forbidden
```
