### ISSUE TITLE
CLI does not allow using grants based on groups

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#891]
**Summary:**
To check user grants the CLI calls `/v1/users/:id/grants` and updates the available destinations based on this. It also needs to get the user' groups, then call the grants endpoint for each of those groups.

**Steps to reproduce:**
1. Deploy infra with only a group grant:
```
  additionalGrants:
    - group: Everyone
      role: cluster-admin
      resource: kubernetes.docker-desktop
```
2. Sign in with a user that belongs to that group. Their access isn't set.
