### ISSUE TITLE
`infra list` shows the same access twice if multiple grants for the same access apply to the user

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#925]
When a user has the same access granted through multiple grants `infra list` should only show the grant once.

**Steps to reproduce:**
1. Create 2 grants for a user, one directly for a user and one for a group they belong to:
```
additionalGrants:
    - group: Everyone
      role: cluster-admin
      resource: kubernetes.docker-desktop
    - user: user@example.com
      role: cluster-admin
      resource: kubernetes.docker-desktop
```
2. Apply this config to the infra server.
3. Login to the Infra server via the CLI.
4. Run `infra list`:
```
% infra list
  DESTINATION                ACCESS         
  kubernetes.docker-desktop  cluster-admin  
  kubernetes.docker-desktop  cluster-admin  
```
