### ISSUE TITLE
`helm install --set-file server.config.import=infra.yaml` yields empty providers and grants

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#935]
`infra.yaml`

```
providers:
  - name: Okta
    url: dev-02708987.okta.com
    clientID: 0oapn0qwiQPiMIyR35d6
    clientSecret: <redacted>

grants:
  - user: jeff@infrahq.com
    role: admin
    resource: infra

  - group: Everyone
    role: view
    resource: kubernetes.docker-desktop # limit access to the `example-cluster` Kubernetes cluster
```

effective configmap:

```
import:
  providers:
    []
  grants:
    []
```
