### ISSUE TITLE
Infra Engine registers as a destination with the internal IP rather than the externally accessible address (ex: the load balancer)

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#955]
**Current behavior:**
The destination is registered with the destination IP.

**Expected behavior:**
The destination registers with an endpoint that is externally accessible (ex: the load balancer's IP).

**Steps to reproduce:**
- Deploy Infra locally with a load balancer for the Infra Engine.
- Observe that on `infra use` that the kube config is set to the internal cluster IP:
```
- cluster:
    certificate-authority-data: ...
    server: https://10.102.253.30:443/proxy
  name: infra:docker-desktop
```
Requests to this internal IP timeout.

**Workaround:**
Manually update the server to what you need in the kubeconfig:
```
- cluster:
    certificate-authority-data: ...
    server: https://localhost:443/proxy
  name: infra:docker-desktop
```
